### ISSUE TITLE
Package libhs was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by 5up3rc** [DigDeeply/gohs-ladon#1]
hi,请问一下libhs的问题该如何解决？
# pkg-config --cflags libhs --static
Package libhs was not found in the pkg-config search path.
Perhaps you should add the directory containing `libhs.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libhs' found
pkg-config: exit status 1

**Comment by DigDeeply** [comment]
参考 [Dockerfile](https://github.com/DigDeeply/gohs-ladon/blob/master/Dockerfile) 看下该设置的环境变量，是否都设置了。
